### ISSUE TITLE
Possibility of using ChatGPT access token instead of OpenAI API key?

### ISSUE THREAD

**Issue by mithras666** [gravelBridge/AutoGPT-BingAI#1]
Hello, great project!

 I'm sorry if this isn't considered an issue, but I don't see a Discussions section, so I thought I'd just post this here.
 Unfortunately, I am not able to pay for API usage, so I was wondering if we could add this plugin to something like this project: 
 https://github.com/IntelligenzaArtificiale/Free-AUTO-GPT-with-NO-API ?
 
 I wonder if it'd be possible to fully replace GPT with Bing instead of using Bing as a "helper", although I've heard Bing is much less willing to think with the user than GPT-3/4.

**Comment by gravelBridge** [comment]
Unfortunately it's not possible, BingAI limits to 20 messages per convo
