### ISSUE TITLE
Error after question ask

### ISSUE THREAD

**Issue by yswlww** [gravelBridge/AutoGPT-BingAI#10]
TypeError: Chatbot.__init__() got an unexpected keyword argument 'cookie_path'

**Comment by bannert1337** [comment]
I have the same problem

**Comment by Sblop** [comment]
same

**Comment by Sigfrodr** [comment]
same

**Comment by Haczan** [comment]
On line 34 of bing_ai.py, please change "Chatbot(cookie_path=cookie_path)" to "Chatbot(cookies=cookies)".

**Comment by NeonN3mesis** [comment]
> On line 34 of bing_ai.py, please change "Chatbot(cookie_path=cookie_path)" to "Chatbot(cookies=cookies)".

This worked!
